# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1366, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1366, 768))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1350, 750))
        self.tabWidget.setMinimumSize(QtCore.QSize(1350, 750))
        self.tabWidget.setMaximumSize(QtCore.QSize(1350, 750))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.btn_attack = QtGui.QPushButton(self.tab)
        self.btn_attack.setGeometry(QtCore.QRect(50, 360, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_attack.setFont(font)
        self.btn_attack.setAutoFillBackground(False)
        self.btn_attack.setObjectName(_fromUtf8("btn_attack"))
        self.lbl_yourip = QtGui.QLabel(self.tab)
        self.lbl_yourip.setGeometry(QtCore.QRect(290, 100, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_yourip.setFont(font)
        self.lbl_yourip.setAutoFillBackground(False)
        self.lbl_yourip.setObjectName(_fromUtf8("lbl_yourip"))
        self.lbl_gatewayip = QtGui.QLabel(self.tab)
        self.lbl_gatewayip.setGeometry(QtCore.QRect(290, 200, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_gatewayip.setFont(font)
        self.lbl_gatewayip.setAutoFillBackground(False)
        self.lbl_gatewayip.setObjectName(_fromUtf8("lbl_gatewayip"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(90, 300, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.cmb_interfaces = QtGui.QComboBox(self.tab)
        self.cmb_interfaces.setGeometry(QtCore.QRect(90, 10, 211, 28))
        self.cmb_interfaces.setAutoFillBackground(False)
        self.cmb_interfaces.setObjectName(_fromUtf8("cmb_interfaces"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(90, 250, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lbl_broadcast = QtGui.QLabel(self.tab)
        self.lbl_broadcast.setGeometry(QtCore.QRect(290, 250, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_broadcast.setFont(font)
        self.lbl_broadcast.setAutoFillBackground(False)
        self.lbl_broadcast.setObjectName(_fromUtf8("lbl_broadcast"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(90, 150, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lbl_subnetmask = QtGui.QLabel(self.tab)
        self.lbl_subnetmask.setGeometry(QtCore.QRect(290, 300, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_subnetmask.setFont(font)
        self.lbl_subnetmask.setAutoFillBackground(False)
        self.lbl_subnetmask.setObjectName(_fromUtf8("lbl_subnetmask"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(90, 200, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lbl_yourmac = QtGui.QLabel(self.tab)
        self.lbl_yourmac.setGeometry(QtCore.QRect(290, 150, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_yourmac.setFont(font)
        self.lbl_yourmac.setAutoFillBackground(False)
        self.lbl_yourmac.setObjectName(_fromUtf8("lbl_yourmac"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(90, 100, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.tbl_localhost = QtGui.QTableWidget(self.tab)
        self.tbl_localhost.setGeometry(QtCore.QRect(500, 20, 591, 421))
        self.tbl_localhost.setObjectName(_fromUtf8("tbl_localhost"))
        self.tbl_localhost.setColumnCount(3)
        self.tbl_localhost.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbl_localhost.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_localhost.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_localhost.setHorizontalHeaderItem(2, item)
        self.tbl_localhost.horizontalHeader().setDefaultSectionSize(150)
        self.tbl_localhost.horizontalHeader().setStretchLastSection(True)
        self.btn_stop = QtGui.QPushButton(self.tab)
        self.btn_stop.setGeometry(QtCore.QRect(280, 360, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_stop.setFont(font)
        self.btn_stop.setObjectName(_fromUtf8("btn_stop"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.table_network = QtGui.QTableWidget(self.tab_2)
        self.table_network.setGeometry(QtCore.QRect(0, 0, 1350, 750))
        self.table_network.setMinimumSize(QtCore.QSize(1350, 750))
        self.table_network.setMaximumSize(QtCore.QSize(1350, 750))
        self.table_network.setAlternatingRowColors(True)
        self.table_network.setGridStyle(QtCore.Qt.SolidLine)
        self.table_network.setObjectName(_fromUtf8("table_network"))
        self.table_network.setColumnCount(9)
        self.table_network.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_network.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_network.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_network.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_network.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_network.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table_network.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table_network.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.table_network.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.table_network.setHorizontalHeaderItem(8, item)
        self.table_network.horizontalHeader().setDefaultSectionSize(140)
        self.table_network.horizontalHeader().setStretchLastSection(True)
        self.table_network.verticalHeader().setCascadingSectionResizes(False)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.table_network_dns = QtGui.QTableWidget(self.tab_3)
        self.table_network_dns.setGeometry(QtCore.QRect(0, 0, 1350, 750))
        self.table_network_dns.setMinimumSize(QtCore.QSize(1350, 750))
        self.table_network_dns.setMaximumSize(QtCore.QSize(1350, 750))
        self.table_network_dns.setObjectName(_fromUtf8("table_network_dns"))
        self.table_network_dns.setColumnCount(3)
        self.table_network_dns.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_network_dns.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_network_dns.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_network_dns.setHorizontalHeaderItem(2, item)
        self.table_network_dns.horizontalHeader().setDefaultSectionSize(200)
        self.table_network_dns.horizontalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.treeWidget = QtGui.QTreeWidget(self.tab_4)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 1350, 750))
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.treeWidget.setHeaderLabels(["IP", "SEND", "RECEIVE"])
        self.treeWidget.setColumnCount(3)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Network Analysis", None))
        self.btn_attack.setText(_translate("MainWindow", "AUTO ARP ATTACK", None))
        self.lbl_yourip.setText(_translate("MainWindow", "*", None))
        self.lbl_gatewayip.setText(_translate("MainWindow", "*", None))
        self.label_5.setText(_translate("MainWindow", "SUBNETMASK   ->", None))
        self.label_4.setText(_translate("MainWindow", "BROADCAST      ->", None))
        self.lbl_broadcast.setText(_translate("MainWindow", "*", None))
        self.label_2.setText(_translate("MainWindow", "YOUR MAC        ->", None))
        self.lbl_subnetmask.setText(_translate("MainWindow", "*", None))
        self.label_3.setText(_translate("MainWindow", "GATEWAY IP      ->", None))
        self.lbl_yourmac.setText(_translate("MainWindow", "*", None))
        self.label.setText(_translate("MainWindow", "YOUR IP             ->", None))
        item = self.tbl_localhost.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IP", None))
        item = self.tbl_localhost.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MAC", None))
        item = self.tbl_localhost.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "VENDOR", None))
        self.btn_stop.setText(_translate("MainWindow", "STOP ARP", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "LOCALHOST", None))
        item = self.table_network.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NO", None))
        item = self.table_network.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TIME", None))
        item = self.table_network.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SOURCE IP", None))
        item = self.table_network.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "SOURCE MAC", None))
        item = self.table_network.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "SOURCE PORT", None))
        item = self.table_network.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "DESTINATION IP", None))
        item = self.table_network.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "DESTINATION MAC", None))
        item = self.table_network.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "DESTINATION PORT", None))
        item = self.table_network.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "INFO", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "MONITOR TCP", None))
        item = self.table_network_dns.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TIME", None))
        item = self.table_network_dns.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP", None))
        item = self.table_network_dns.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "QUERY", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "MONITOR UDP", None))
        self.tab_4.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "UTİLS", None))

